name: Docker

on:
  pull_request:
    branches-ignore: [ "beta*", "dev*", "next*" ]
  push:
    branches-ignore: [ "beta*", "dev*", "next*" ]
    tags: [ "v*.*.*" ]
  release:
    types: [ published ]
  repository_dispatch:
    types: [ docker ]
  schedule:
    - cron: "30 9 * * *" # 9:30 UTC
  workflow_dispatch:

env:
  REGISTRY: hub.docker.com

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: rust
        dockerfile: rust/Dockerfile
        name: ${{ secrets.DOCKERHUB_USERNAME }}/rust
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        snapshot: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
  rust-wasm:
    needs: [ rust ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: rust/wasm
        dockerfile: rust/wasm/Dockerfile
        name: ${{ secrets.DOCKERHUB_USERNAME }}/rust-wasm
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        snapshot: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
  wasm-dev:
    needs: [ rust-wasm ]
    strategy:
      matrix:
        target: [ "dioxus", "trunkrs" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish (${{ matrix.target }})
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        buildoptions: "--target ${{ matrix.target }}"
        context: rust/wasm
        dockerfile: rust/wasm/dev.dockerfile
        name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.target }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        snapshot: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
  wasmer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: misc/wasm
        dockerfile: misc/wasm/wasmer.dockerfile
        name: ${{ secrets.DOCKERHUB_USERNAME }}/wasmer
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64
        snapshot: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}