name: Docker

on:
  pull_request:
    branches-ignore: [ "beta*", "dev*", "next*" ]
  push:
    branches-ignore: [ "beta*", "dev*", "next*" ]
    tags: [ "v*.*.*" ]
  release:
    types: [ published ]
  repository_dispatch:
    types: [ docker ]
  schedule:
    - cron: "30 9 * * *" # 9:30 UTC
  workflow_dispatch:

env:
  REGISTRY: hub.docker.com


jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: rust/wasm
        dockerfile: rust/wasm/Dockerfile
        name: ${{ secrets.DOCKERHUB_USERNAME }}/rust-wasm
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        snapshot: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        context: rust/wasm
        dockerfile: rust/wasm/trunk.dockerfile
        name: ${{ secrets.DOCKERHUB_USERNAME }}/trunkrs
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        snapshot: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
